/*
 * Copyright (C) 2009 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* Changes from Qualcomm Innovation Center are provided under the following license:
 * Copyright (c) 2022-2023 Qualcomm Innovation Center, Inc. All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause-Clear
 */

#include <stdio.h>
#include <unistd.h>
#include <stdlib.h>
#include <string.h>
#include <inttypes.h>


#include <libxml/parser.h>
#include <libxml/tree.h>
#include <sstream>
#include <chrono>
#include <limits>
#include <map>
#include <string>
#include <vector>

#include <sys/stat.h>
#include <fcntl.h>

#include "edify/expr.h"
#include "updater.h"
#include "install.h"
#include "blockimg.h"
#include "minzip/Zip.h"
#include "minzip/SysUtil.h"
#include "otafault/config.h"
#include "common.h"

#ifdef TARGET_SUPPORTS_AB
#ifndef TARGET_NAD_OTA
#include <libabctl.h>
#else
#include <nad-ab-al.h>
#include <limits.h>
#endif
const char* slot_suffix_arr[] = {"_a", "_b", NULL};
#else
const char* slot_suffix_arr[] = {"", "", ""};
#endif
// for non-AB case, slot_suffix_arr[0] will always be NULL and same code can be used
// to get mtd block using volume name
int boot_slot, inactive_slot;
// Generated by the makefile, this function defines the
// RegisterDeviceExtensions() function, which calls all the
// registration functions for device-specific extensions.
#ifndef USE_LE_MODE
#include "register.inc"
#else
extern void Register_librecovery_updater_msm();
#endif

// Where in the package we expect to find the edify script to execute.
// (Note it's "updateR-script", not the older "update-script".)
#define SCRIPT_NAME "META-INF/com/google/android/updater-script"
#if defined(TARGET_SUPPORTS_MIRROR_AB_COPY) || defined(TARGET_SUPPORTS_MPLANE_SPEC)
#define MIRROR_SCRIPT_NAME "META-INF/com/google/android/updater-mirror-script"
#define INSTALL_SCRIPT_NAME "META-INF/com/google/android/updater-install-script"
#define MANIFEST_FILE_NAME "manifest.xml"
#define MANIFEST_FILE_PATH "/tmp/manifest.xml"
#define COMMON_MANIFEST_FILE_PATH "/tmp/common_manifest.xml"
#define PATH_MAX 100
#define PRODUCT_INFO "/etc/device_info.xml"
#define COMMON_MANIFEST_FILE_NAME "common_manifest.xml"
#endif

extern bool have_eio_error;

struct selabel_handle *sehandle;

#ifdef TARGET_NAD_OTA
int set_nad_update_status( const char * value ) {
    FILE* status_fp = fopen(NAD_UPDATE_STATUS, "a+");
    if (status_fp != nullptr) {
        char buf[PATH_MAX];
        snprintf(buf, PATH_MAX, "%s", value);
        size_t bytes;
        fwrite(buf, 1, 8, status_fp);
        fflush(status_fp);
        if (ferror(status_fp)) printf("Error in %s\n(%s)\n", NAD_UPDATE_STATUS, strerror(errno));
        fclose(status_fp);
        return 0;
    } else {
        printf(" set nad ota cookie error \n");
    }
    return -1;
}
#endif

#if defined(TARGET_SUPPORTS_MIRROR_AB_COPY) || defined(TARGET_SUPPORTS_MPLANE_SPEC)

const char* get_build_id_from_manifest(const ZipArchive *pArchive) {
    xmlDocPtr deviceInfo;
    xmlNodePtr deviceInfoRootNode = NULL;
    xmlNodePtr deviceInfoObjNode, deviceInfoChildNode;
    deviceInfo = xmlReadFile(PRODUCT_INFO, "UTF-8", XML_PARSE_RECOVER);
    const char *input_vendor = nullptr, *input_code = nullptr, *input_name = nullptr;
    if(NULL == deviceInfo) {
        printf("XML Document not parsed successfully.\n ");
        return nullptr;
    }

    deviceInfoRootNode = xmlDocGetRootElement(deviceInfo);
    if(NULL == deviceInfoRootNode) {
        printf("Empty XML document \n");
        xmlFreeDoc(deviceInfo);
        return nullptr;
    }
    for(deviceInfoObjNode = deviceInfoRootNode->children; deviceInfoObjNode; deviceInfoObjNode = deviceInfoObjNode->next) {
        if (deviceInfoObjNode->type != XML_ELEMENT_NODE) {
            continue;
        }

        printf("Parsing element , line %u: name=%s \n", deviceInfoObjNode->line, (char*)deviceInfoObjNode->name);
        if (deviceInfoObjNode->name !=nullptr && strncmp((const char *)deviceInfoObjNode->name, "Device_info", strlen("Device_info")) == 0) {
            input_vendor = (char * ) xmlGetProp(deviceInfoObjNode, BAD_CAST "vendor");
            input_code = (char *) xmlGetProp(deviceInfoObjNode, BAD_CAST "code");
            input_name = (char *) xmlGetProp(deviceInfoObjNode, BAD_CAST "name");
        }
    }
    printf("input_vendor: %s, input_code: %s, input_name: %s", input_vendor, input_code, input_name);
    xmlDocPtr commonManifest;
    xmlNodePtr commonManifestRootNode = NULL;
    xmlNodePtr objNode, childNode;

    const ZipEntry* manifest_entry = mzFindZipEntry(pArchive, COMMON_MANIFEST_FILE_NAME);
    if (manifest_entry == NULL) {
        printf("failed to find %s\n", COMMON_MANIFEST_FILE_NAME);
        return nullptr;
    }
    const char* manifest = COMMON_MANIFEST_FILE_PATH;
    unlink(manifest);
    int manifest_fd = creat(manifest, 0644);
    if (manifest_fd < 0) {
        printf("%s: Can't make\n", manifest);
        return nullptr;
    }
    bool ok = mzExtractZipEntryToFile(pArchive, manifest_entry, manifest_fd);
    close(manifest_fd);
    if (!ok) {
        printf("%s: Can't extract from zip\n", COMMON_MANIFEST_FILE_NAME);
        return nullptr;
    }
    printf("start to load xml: %s", COMMON_MANIFEST_FILE_NAME);

    commonManifest = xmlReadFile(COMMON_MANIFEST_FILE_PATH, "UTF-8", XML_PARSE_RECOVER);
    if(NULL == commonManifest) {
        printf("XML Document not parsed successfully.\n ");
        return nullptr;
    }

    commonManifestRootNode = xmlDocGetRootElement(commonManifest);
    if(NULL == commonManifestRootNode) {
        printf("Empty XML document \n");
        xmlFreeDoc(commonManifest);
        return nullptr;
    }
    for(objNode = commonManifestRootNode->children; objNode; objNode = objNode->next) {
        if (objNode->type != XML_ELEMENT_NODE) {
            continue;
        }
        printf("Parsing element , line %u: name=%s \n", objNode->line, (char*)objNode->name);
        if (objNode->name != nullptr && strncmp((const char *)objNode->name, "products", strlen("products")) == 0) {
            for(childNode = objNode->children; childNode; childNode = childNode->next) {
                if (childNode->type != XML_ELEMENT_NODE)
                    continue;
                printf("Parsing element , line %u: name=%s \n",childNode->line, (char*)childNode->name);
                    if (childNode->name != nullptr && strncmp((const char *)childNode->name, "product", strlen("product")) == 0) {
                        const char *product_vendor = nullptr, *product_code = nullptr, *product_name = nullptr;
                        product_vendor = (char * ) xmlGetProp(childNode, BAD_CAST "vendor");
                        product_code = (char *) xmlGetProp(childNode, BAD_CAST "code");
                        product_name = (char *) xmlGetProp(childNode, BAD_CAST "name");
                        if(product_vendor != nullptr && product_code != nullptr && product_name != nullptr) {
                            if (strncmp(product_vendor, input_vendor, strlen(product_vendor)) == 0 && strncmp(product_code, input_code, strlen(product_code)) == 0 && strncmp(product_name, input_name, strlen(product_name)) == 0) {
                                return (char *) xmlGetProp(childNode, BAD_CAST "build-Id");
                            }
                        }
                    }
            }
        }
    }
    return nullptr;
}
#endif

int main(int argc, char** argv) {
    // Various things log information to stdout or stderr more or less
    // at random (though we've tried to standardize on stdout).  The
    // log file makes more sense if buffering is turned off so things
    // appear in the right order.
    setbuf(stdout, NULL);
    setbuf(stderr, NULL);

    if (argc != 4 && argc != 5) {
        printf("unexpected number of arguments (%d)\n", argc);
        return 1;
    }

#ifdef TARGET_SUPPORTS_MIRROR_AB_COPY
    printf("updater number of arguments (%d)\n", argc);
    for (int arg = 0; arg < argc; arg++) {
        printf(" \"%s\"", argv[arg]);
    }
    printf("\n");
#endif

    char* version = argv[1];
    if ((version[0] != '1' && version[0] != '2' && version[0] != '3') ||
        version[1] != '\0') {
        // We support version 1, 2, or 3.
        printf("wrong updater binary API; expected 1, 2, or 3; "
                        "got %s\n",
                argv[1]);
        return 2;
    }

    // Set up the pipe for sending commands back to the parent process.

    int fd = atoi(argv[2]);
    FILE* cmd_pipe = fdopen(fd, "wb");
    if(cmd_pipe == NULL) {
       printf("cmd_pipe is NULL so aborting!\n");
       return 2;
    }
    setlinebuf(cmd_pipe);

#ifdef TARGET_SUPPORTS_AB
#ifndef TARGET_NAD_OTA
    printf (" call libabctl \n");
    boot_slot = libabctl_getBootSlot();
#else
    printf (" call nadabctl \n");
    boot_slot = libnadab_get_boot_slot();
#endif
    if (boot_slot == -1) {
        printf("That's odd.. I was told that A/B boot support be present\n"
               "But libabctl_getBootSlot() returned -1, aborting!\n");
        return 1;
    }
    // Set the inactive slot to the non-boot slot (1->0, 0->1)
    inactive_slot = (boot_slot + 1)%2;
    printf("boot_slot = %s, inactive_slot = %s\n", slot_suffix_arr[boot_slot],
            slot_suffix_arr[inactive_slot]);
#endif

    // Extract the script from the package.

    const char* package_filename = argv[3];
    MemMapping map;
    if (sysMapFile(package_filename, &map) != 0) {
        printf("failed to map package %s\n", argv[3]);
        return 3;
    }
    ZipArchive za = {0};
    int err;
    err = mzOpenZipArchive(map.addr, map.length, &za);
    if (err != 0) {
        printf("failed to open package %s: %s\n",
               argv[3], strerror(err));
        fprintf(cmd_pipe, "ui_print failed to open package %s: %s\n",
                package_filename, strerror(err));
        return 3;
    }
#ifndef USE_LE_MODE
    ota_io_init(&za);
#endif

#if defined(TARGET_SUPPORTS_MIRROR_AB_COPY) || defined(TARGET_SUPPORTS_MPLANE_SPEC)
    char* copy_mirror = argv[4];
    char* script_name = NULL;
    if(copy_mirror != NULL)
    {
        printf(" copy_mirror arg : %s \n",copy_mirror);
    }
    if (argv[4] != NULL) {
        if (strcmp(argv[4], "copy_to_inactive") == 0){
        //if (strcmp(copy_mirror, "copy_to_inactive")){
            script_name = MIRROR_SCRIPT_NAME;
        } else if(strcmp(argv[4], "only_installation") == 0){
            script_name = INSTALL_SCRIPT_NAME;
        }
    } else {
        script_name = SCRIPT_NAME;
    }
    const char *build_id = get_build_id_from_manifest(&za);
    char buf[PATH_MAX];
    if (build_id != nullptr){
        snprintf(buf, PATH_MAX, "build-id%s/%s", build_id, script_name);
    }
    printf(" updater using  script %s \n",buf);
    const ZipEntry* script_entry = mzFindZipEntry(&za, buf);
#else
    const ZipEntry* script_entry = mzFindZipEntry(&za, SCRIPT_NAME);
#endif
    if (script_entry == NULL) {
        printf("failed to find %s in %s\n", SCRIPT_NAME, package_filename);
        fprintf(cmd_pipe, "ui_print failed to find %s in %s\n", SCRIPT_NAME, package_filename);
        return 4;
    }

    char* script = reinterpret_cast<char*>(malloc(script_entry->uncompLen+1));
    if (!mzReadZipEntry(&za, script_entry, script, script_entry->uncompLen)) {
        printf("failed to read script from package\n");
        fprintf(cmd_pipe, "ui_print failed to read script from package\n");
        return 5;
    }
    script[script_entry->uncompLen] = '\0';

    // Configure edify's functions.

    RegisterBuiltins();
    RegisterInstallFunctions();
    RegisterBlockImageFunctions();
#ifdef USE_LE_MODE
    Register_librecovery_updater_msm();
#else
    RegisterDeviceExtensions();
#endif
    FinishRegistration();

    // Parse the script.

    Expr* root;
    int error_count = 0;
    int error = parse_string(script, &root, &error_count);
    if (error != 0 || error_count > 0) {
        printf("%d parse errors\n", error_count);
        fprintf(cmd_pipe, "ui_print %d parse errors\n", error_count);
        return 6;
    }

    struct selinux_opt seopts[] = {
      { SELABEL_OPT_PATH, "/file_contexts" }
    };

    sehandle = selabel_open(SELABEL_CTX_FILE, seopts, 1);

    if (!sehandle) {
        fprintf(cmd_pipe, "ui_print Warning: No file_contexts\n");
    }

    // read the partition mapping
    if (IS_LE_MODE()) {
        load_volume_table(cmd_pipe);
    }

    // Evaluate the parsed script.

    UpdaterInfo updater_info;
    updater_info.cmd_pipe = cmd_pipe;
    updater_info.package_zip = &za;
    updater_info.version = atoi(version);
    updater_info.package_zip_addr = map.addr;
    updater_info.package_zip_len = map.length;

    State state;
    state.cookie = &updater_info;
    state.script = script;
    state.errmsg = NULL;

    if (argc == 5) {
        if (strcmp(argv[4], "retry") == 0) {
            state.is_retry = true;
        } else {
            printf("unexpected argument: %s", argv[4]);
        }
    }

    char* result = Evaluate(&state, root);

    if (have_eio_error) {
        fprintf(cmd_pipe, "retry_update\n");
    }

    if (result == NULL) {
        if (state.errmsg == NULL) {
            printf("script aborted (no error message)\n");
            fprintf(cmd_pipe, "ui_print script aborted (no error message)\n");
        } else {
            printf("script aborted: %s\n", state.errmsg);
            char* saveptr =NULL;
            char* line = strtok_r(state.errmsg, "\n", &saveptr);
            while (line) {
                // Parse the error code in abort message.
                // Example: "E30: This package is for bullhead devices."
                if (*line == 'E') {
                    if (sscanf(line, "E%u: ", &state.error_code) != 1) {
                         printf("Failed to parse error code: [%s]\n", line);
                    }
                }
                fprintf(cmd_pipe, "ui_print %s\n", line);
                line = strtok_r(NULL, "\n", &saveptr);
            }
            fprintf(cmd_pipe, "ui_print\n");
        }

        if (state.error_code != kNoError) {
            fprintf(cmd_pipe, "log error: %d\n", state.error_code);
            // Cause code should provide additional information about the abort;
            // report only when an error exists.
            if (state.cause_code != kNoCause) {
                fprintf(cmd_pipe, "log cause: %d\n", state.cause_code);
            }
        }

        free(state.errmsg);
        if (IS_LE_MODE()) {
            free_volume_table();
        }

        return 7;
    } else {
        fprintf(cmd_pipe, "ui_print script succeeded: result was [%s]\n", result);
        free(result);
    }

    if (updater_info.package_zip) {
        mzCloseZipArchive(updater_info.package_zip);
    }
    sysReleaseMap(&map);
    free(script);
    if (IS_LE_MODE()) {
        free_volume_table();
    }
    printf("return 0 from updater ");
    return 0;
}
